k9s:
  # Live view settings
  liveViewAutoRefresh: true
  refreshRate: 2
  maxConnRetry: 5

  # Access mode
  readOnly: false

  # UI Configuration
  ui:
    enableMouse: true
    headless: true
    reactive: true
    skin: transparent
    logoless: false
    crumbsless: false
    noIcons: false

  # Logging
  logger:
    tail: 200
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false

  # Shell pod settings
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
